name: all_nations
description: Dag Heward-Mills All Nations app

version: 0.0.1+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  auto_route: ^6.2.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  # epub_view: 
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.2.19
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  injectable: ^2.1.1
  internet_file: ^1.2.0
  json_annotation: ^4.8.0
  line_awesome_flutter: ^2.0.0
  moment_dart: ^0.17.4
  responsive_framework: ^0.2.0
  share_plus: ^6.3.1
  skeletons: ^0.0.3
  url_launcher: ^6.1.10
  vocsy_epub_viewer: ^2.0.0
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^6.2.0
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.12.0
  freezed: ^2.3.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/logo/
    - assets/images/illustrations/
    - assets/images/collections/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icons/icon.png"
  adaptive_icon_background: "#1A2C42"
  adaptive_icon_foreground: "assets/images/icons/android12_icon.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#EBECEE"
  color_dark: "#131314"
  image: "assets/images/logo/splash.png"
  image_dark: "assets/images/logo/splash_dark.png"
  # branding_dark: "assets/images/logo/dhm_white_splash.png"
  # branding: "assets/images/logo/dhm_black_splash.png"
  # branding_mode: bottom
  android_12:
    color: "#EBECEE"
    color_dark: "#131314"
    image: "assets/images/logo/splash.png"
    image_dark: "assets/images/logo/splash_dark.png"
    # branding_dark: "assets/images/logo/dhm_white_splash.png"
    # branding: "assets/images/logo/dhm_black_splash.png"
    # branding_mode: bottom
